services:
  db:
    image: postgres
    user: postgres
    restart: always
    container_name: "trase_db"
    ports:
      - 5432:5432
    environment:
      - SHARED_PASSWORD=password
      - POSTGRES_PASSWORD=posgres349  
      - POSTGRES_DB_NAME=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./db/scripts/:/docker-entrypoint-initdb.d/
      - ./db/data:/var/lib/postgresql/data
  api:
    container_name: trase_api
    build: ./api
    hostname: api
    volumes:
      - ./api:/api
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=posgres349
      - POSTGRES_DB_NAME=postgres
      - POSTGRES_DB_HOST=db
    ports:
      - "8080:4444"
